### ISSUE TITLE
Refresh Code generation website doesn't use correct scopes

### ISSUE THREAD

**Issue by j3ns3n** [l3d00m/spotispy#2]
You have to add "%20user-read-currently-playing%20user-read-playback-state" to the scopes in the URL of the Spotify login page you are redirected to in order for the correct access token to be generated.

EG:
https://accounts.spotify.com/en/authorize?client_id=XXX&response_type=code&redirect_uri=https:%2F%2Fgrant.outofindex.com%2Fconnect%2Fspotify%2Fcallback&scope=streaming%20user-read-currently-playing%20user-read-playback-state&show_dialog=true

**Comment by l3d00m** [comment]
I'm wondering how I managed to create a refresh token without adding that, pretty sure I used that site too. Anyways, I'll add a link to this issue in the readme
